# This is an example OpenAPI specification
# It illustrates a dependency of the Petstore OpenDep specification.
---
openapi: "3.0.1"

info:
  title: Sample Petstore pet naming service
  description: This is a sample OpenAPI specification describing a service for suggesting pet names.
  contact:
    name: Pete Cornish
    url: https://github.com/opendeps
    email: opendeps@example.com
  version: "2.0.0"

paths:
  /names:
    get:
      responses:
        '200':
          description: Lists supplies for sale
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples:
                namesExample:
                  value:
                    [
                      "Fluffy",
                      "Paws"
                    ]
  /healthz:
    get:
      responses:
        '200':
          description: Healthcheck endpoint
          content:
            text/plain:
              schema:
                type: string
              examples:
                success:
                  value: "ok"

servers:
  - description: Local development
    url: http://localhost:8080
