# This is an example OpenAPI specification
# It illustrates a dependency of the Petstore OpenDeps specification.
---
openapi: "3.0.1"

info:
  title: Sample Petstore stock service
  description: This is a sample OpenAPI specification describing a service for managing stock.
  contact:
    name: Pete Cornish
    url: https://github.com/opendeps
    email: opendeps@example.com
  version: "1.0.0"

paths:
  /products:
    get:
      security:
        - BasicAuth: []
      responses:
        '200':
          description: Lists products for sale
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - sku
                    - name
                    - price
                  properties:
                      sku:
                        type: string
                      name:
                        type: string
                      price:
                        type: number
                        format: double
              examples:
                itemsExample:
                  value:
                    [
                      { sku: "fb01", "name": "Food bowl", "price": 3.99 },
                      { sku: "br06", "name": "Brush", "price": 2.99 }
                    ]
  /healthz:
    get:
      responses:
        '200':
          description: Healthcheck endpoint
          content:
            text/plain:
              schema:
                type: string
              examples:
                success:
                  value: "ok"

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

servers:
  - description: Local development
    url: http://localhost:8080
