name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Imposter CLI
        run: curl -L https://raw.githubusercontent.com/gatehill/imposter-cli/main/install/install_imposter.sh | bash -

      - name: Install core module dependencies
        run: npm install
      - name: Pull test dependencies
        run: |
          docker pull outofcoffee/imposter:latest
          docker pull outofcoffee/imposter:2.4.12
      - name: Test core module
        run: npm test
      - name: Build core module
        run: npm run build

      - name: Install sample project dependencies
        run: |
          npm run prep-sample
          npm install
        working-directory: sample
      - name: Test sample project
        run: npm test
        working-directory: sample

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
