name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Imposter CLI
        run: curl -L https://raw.githubusercontent.com/gatehill/imposter-cli/main/install/install_imposter.sh | bash -

      - name: Install core module dependencies
        run: npm install
      - name: Pull test dependencies
        run: |
          imposter engine pull --version 3.33.4
          imposter engine pull --version latest
      - name: Test core module
        run: |
          export IMPOSTER_DOCKER_CONTAINERUSER="$(id -u)"
          npm test
      - name: Build core module
        run: npm run build

      - name: Install sample project dependencies
        run: |
          npm run prep-sample
          npm install
        working-directory: sample
      - name: Test sample project
        working-directory: sample
        run: |
          export IMPOSTER_DOCKER_CONTAINERUSER="$(id -u)"
          npm test

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
